// Glossary entries — used by Education Mode + Glossary panel.
export interface GlossaryEntry {
  term: string;
  definition: string;
  whyItMatters: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: "pI (Isoelectric Point)",
    definition: "The pH at which a protein carries no net electrical charge.",
    whyItMatters: "Determines solubility — proteins are least soluble at their pI, useful for purification and predicting in vivo behavior." },
  { term: "GRAVY",
    definition: "Grand Average of Hydropathicity — the mean Kyte-Doolittle hydropathy of all residues.",
    whyItMatters: "Positive GRAVY suggests a hydrophobic / membrane-associated protein; negative suggests soluble." },
  { term: "Aliphatic Index",
    definition: "Relative volume of aliphatic side chains (Ala, Val, Ile, Leu).",
    whyItMatters: "Higher values correlate with thermostability — used to predict whether a protein survives at high temperatures." },
  { term: "Instability Index",
    definition: "Guruprasad's score predicting in-vitro stability from dipeptide composition.",
    whyItMatters: "Below 40 suggests a stable protein; above 40 predicts rapid degradation in test tubes." },
  { term: "BLOSUM62",
    definition: "A substitution matrix scoring how often one amino acid is replaced by another in evolution.",
    whyItMatters: "Positive scores mean the substitution is evolutionarily acceptable; negative scores suggest functional disruption." },
  { term: "Ramachandran Plot",
    definition: "A 2D map of φ vs. ψ backbone dihedral angles for every residue.",
    whyItMatters: "Reveals whether residues adopt allowed conformations — outliers often indicate model errors or strained residues." },
  { term: "B-factor",
    definition: "Atomic displacement parameter — how much an atom 'wiggles' around its mean position.",
    whyItMatters: "Higher B-factor = more flexible region; loops and surface side chains are typically high, cores typically low." },
  { term: "RSRZ (Real Space R-value Z-score)",
    definition: "Standardized score of how well a residue's atoms fit the experimental electron density.",
    whyItMatters: "|RSRZ| > 2 marks an outlier — the residue may be misplaced or poorly resolved." },
  { term: "pLDDT",
    definition: "AlphaFold's per-residue confidence score from 0–100.",
    whyItMatters: ">90 is very high (often crystal-quality); <50 likely disordered or unfolded in isolation." },
  { term: "Clashscore",
    definition: "Number of serious atomic clashes per 1000 atoms.",
    whyItMatters: "Lower is better — high clashscores indicate over-fitted or strained model geometry." },
  { term: "Solvent Accessible Surface Area (SASA)",
    definition: "Surface area of a residue exposed to solvent water.",
    whyItMatters: "Buried residues form the hydrophobic core; exposed residues drive interactions and folding." },
  { term: "Disulfide Bond",
    definition: "Covalent S-S bond between two cysteine side chains.",
    whyItMatters: "Stabilizes secreted proteins and stitches together antibody chains." },
  { term: "Hydropathy (Kyte-Doolittle)",
    definition: "An empirical scale ranking each amino acid from most hydrophilic (-4.5) to most hydrophobic (+4.5).",
    whyItMatters: "Sliding-window plots reveal transmembrane helices and exposed/buried regions." },
  { term: "Ångström (Å)",
    definition: "Length unit equal to 10⁻¹⁰ m — the natural scale of atomic distances.",
    whyItMatters: "Bond lengths are 1–2 Å; protein structures are typically 20–100 Å across." },
  { term: "TM-score",
    definition: "Template Modeling score — a length-independent measure of structural similarity (0–1).",
    whyItMatters: ">0.5 indicates the same fold; >0.8 means near-identical topology." },
  { term: "Active Site",
    definition: "The pocket where an enzyme binds substrate and catalyzes reaction.",
    whyItMatters: "Mutations here usually abolish function — the molecular target of most drugs." },
  { term: "Allostery",
    definition: "Long-range communication where binding at one site changes activity at a distant site.",
    whyItMatters: "Allows feedback regulation — hemoglobin's cooperative O₂ binding is the classic example." },
  { term: "Heteroatom (HETATM)",
    definition: "PDB record for non-standard atoms — ligands, cofactors, metals, water.",
    whyItMatters: "Tells us what the protein binds: drugs, substrates, cofactors needed for function." },
];
